apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-pack.fullname" . }}-svc
  labels:
    app: keycloak-pack
  {{- include "keycloak-pack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: keycloak-pack
  {{- include "keycloak-pack.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.svc.ports | toYaml | nindent 2 -}}