# 베이스 이미지로 OpenResty의 공식 Docker 이미지를 선택합니다.
# OpenResty는 NGINX 기반의 웹 플랫폼으로, NGINX, ngx_devel_kit, LuaJIT,
# lua-nginx-module, lua-cjson, lua-resty-string 등의 기본적인 종속성을 포함하고 있습니다.
FROM openresty/openresty:latest


# 필요한 시스템 패키지들을 설치하기 위해 패키지 관리자를 업데이트합니다.
RUN ["apt-get", "update"]

# libssl-dev와 luarocks를 설치합니다.
# - libssl-dev: SSL/TLS 지원을 위한 라이브러리
# - luarocks: Lua 패키지 관리자로, 다양한 Lua 라이브러리를 쉽게 설치할 수 있게 해줍니다.
RUN ["apt-get", "install", "-y", "libssl-dev", "luarocks"]


# LuaRocks의 최신 버전을 수동으로 다운로드 및 설치
RUN apt-get install -y wget unzip build-essential libreadline-dev && \
    wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz && \
    tar -xzvf luarocks-3.9.2.tar.gz && \
    cd luarocks-3.9.2 && \
    ./configure && \
    make build && \
    make install && \
    cd .. && \
    rm -rf luarocks-3.9.2 luarocks-3.9.2.tar.gz


# luarocks로 필요한 최신 버전으로 업그레이드
#RUN ["luarocks", "install", "luarocks"]


# luarocks를 사용하여 lua-resty-openidc 및 관련 종속성을 설치합니다.
# - lua-resty-openidc: OpenID Connect와 OAuth 2.0 프로토콜을 위한 라이브러리
# - lua-resty-http: HTTP 클라이언트 기능을 제공하는 라이브러리
# - lua-resty-session: 세션 관리를 위한 라이브러리
# - lua-resty-jwt: JWT 파싱 및 검증을 위한 라이브러리
RUN ["luarocks", "install", "lua-resty-openidc"]
RUN ["luarocks", "install", "lua-resty-http"]
RUN ["luarocks", "install", "lua-resty-session"]
RUN ["luarocks", "install", "lua-resty-jwt"]


# 불필요한 패키지 목록을 삭제합니다.
RUN ["rm", "-rf", "/var/lib/apt/lists/*"]



# 원하는 설정 파일, 웹 페이지, 스크립트 등을 추가할 수 있습니다.
# 예를 들면, 아래와 같이 NGINX 설정 파일을 추가할 수 있습니다.
# COPY ./my_nginx_config.conf /usr/local/openresty/nginx/conf/nginx.conf

# NGINX를 데몬 모드로 실행하지 않고 포어그라운드에서 실행하도록 명령어를 설정합니다.
# 이렇게 설정하면 Docker 컨테이너가 NGINX 프로세스와 함께 종료되게 됩니다.
CMD ["nginx", "-g", "daemon off;"]


#컨테이너가 포트 80을 노출하도록 지정한다.
#외부에서 HTTP 트래픽을 컨테이너 내의 NGINX에 전달할 수 있도록 한다.
EXPOSE 80

#lua-resty-openidc를 위한 nginx.conf 설정을 /etc/nginx/conf.d/ 디렉토리에 복사.
COPY server_setting.conf /etc/nginx/conf.d/server_setting.conf
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf 

#lua-resty-openidc에서 사용중인 lua 파일을 ./usr/local/openresty/lualib/resty 경로에 옮긴다.
COPY tests/ /usr/local/openresty/lualib/resty/


# html 파일을 컨테이너 내 /usr/local/openresty/nginx/html 디렉토리로 복사
COPY redirect.html /usr/local/openresty/nginx/html/redirect.html
COPY master.html /usr/local/openresty/nginx/html/master.html
COPY haneul.html /usr/local/openresty/nginx/html/haneul.html
COPY loginOut.html /usr/local/openresty/nginx/html/loginOut.html
COPY loginOut.html /usr/local/openresty/nginx/html/40x.html
